[package]
name = "gridgames-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
clap = { version = "4.5", features = ["derive"] }

[lints.clippy]
needless_range_loop = "allow"
new_without_default = "allow"
